### ISSUE TITLE
project.py içinde cuda=True yapınca hata

### ISSUE THREAD

**Issue by ebektas** [mfsuve/YOLO_Object_Detection#1]
Traceback (most recent call last):
  File "project.py", line 32, in <module>
    output = model(tensor, CUDA=True).numpy()
  File "/home/emre/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/emre/depo2/yolo/py-files/darknet.py", line 217, in forward
    x = predict_transform(x, inp_dim, anchors, num_classes, CUDA)
  File "/media/emre/depo2/yolo/py-files/util.py", line 80, in predict_transform
    prediction[:, :, :2] += x_y_offset
RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor

**Comment by ebektas** [comment]
Traceback (most recent call last):
  File "project.py", line 32, in <module>
    output = model(tensor, CUDA=True).cpu().numpy()
  File "/home/emre/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/emre/depo2/yolo/py-files/darknet.py", line 182, in forward
    x = self.module_list[i](x)
  File "/home/emre/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emre/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/emre/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emre/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by ebektas** [comment]
yukardakiler düzeldi, vidyo sınıflandırma bitirip kapanınca şu geliyor: bilmem önemli mi
Traceback (most recent call last):
  File "project.py", line 21, in <module>
    h, w, _ = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by mfsuve** [comment]
Bu hata eğer videonun sonunda geliyorsa sıkıntı değil bence, zaten vido ile
değil direk resim ile test edecekler heralde

**Comment by ebektas** [comment]
https://drive.google.com/open?id=1vaD5A7EuIO5lvYiNN1Upx6nAcQ07B_M4

**Comment by ebektas** [comment]
https://drive.google.com/open?id=1YXM65X4EOMVB18AeDkQAFijIDWPhB8_f

some data with random yolo label

**Comment by ebektas** [comment]
Output from predict:
C:\Users\Eb\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
[{'bndbox': {'xmax': 1748.3564, 'xmin': 1656.3779, 'ymax': 959.97314, 'ymin': 742.95483, 'name': 'Pedestrian', 'confidence': 0.99967206}}, {'bndbox': {'xmax': 1820.4086, 'xmin': 1730.0109, 'ymax': 956.9774, 'ymin': 739.43994, 'name': 'Pedestrian', 'confidence': 0.9997663}}, {'bndbox': {'xmax': 1222.167, 'xmin': 1205.9597, 'ymax': 836.4831, 'ymin': 791.62335, 'name': 'Pedestrian', 'confidence': 0.9310432}}, {'bndbox': {'xmax': 497.48773, 'xmin': 21.000778, 'ymax': 1075.7695, 'ymin': 700.68396, 'name': 'Car', 'confidence': 0.9813921}}, {'bndbox': {'xmax': 845.40765, 'xmin': 765.7, 'ymax': 897.9188, 'ymin': 787.87317, 'name': 'Car', 'confidence': 0.9358269}}, {'bndbox': {'xmax': 1175.5259, 'xmin': 821.74207, 'ymax': 1043.4852, 'ymin': 727.4963, 'name': 'Car', 'confidence': 0.74093103}}, {'bndbox': {'xmax': 1544.5735, 'xmin': 1431.1667, 'ymax': 928.2759, 'ymin': 852.4088, 'name': 'Car', 'confidence': 0.6534355}}, {'bndbox': {'xmax': 782.79877, 'xmin': 449.43646, 'ymax': 983.22003, 'ymin': 702.89557, 'name': 'Truck', 'confidence': 0.5620018}}, {'bndbox': {'xmax': 1177.0741, 'xmin': 817.8071, 'ymax': 1078.8032, 'ymin': 721.2555, 'name': 'Truck', 'confidence': 0.51504713}}]
Output from predict:
